---
functional:
  - пользователь должен иметь возможность зарегистрироваться
  - пользователь должен иметь возможность войти по e-mail
  - пользователь должен иметь возможность авторизоваться через соцсети
  - пользователь должен иметь возможность открыть свой профиль
  - пользователь должен иметь возможность выбирать уровень сложности
  - пользователь должен иметь возможность выбирать соперника или бот
  - пользователь должен иметь возможность выбирать язык программирования
  - пользователь должен иметь возможность выбирать время раунда
  - пользователь должен иметь возможность сделать сброс в редакторе решения задачи
  - пользователь должен иметь возможность выбирать задачи
  - пользователь должен иметь возможность выйти из игры в любой момент
  - пользователь должен иметь возможность общаться с другими пользователями
  - пользователь должен иметь возможность удалить свой аккаунт
non-functional:
  - сайт должен быть безопасным и защищать данные пользователя
  - сайт должен быть удобным на мобильном устройстве
  - сайт должен быть протестирован на совместимость с последними версиями браузеров
  - сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - сайт мультиязычен
  - сайт переходит на главную страницу по клику на логотип
  - рейтинг участника отображается на главной странице сайта под каждым username
  - пользователи сортируются по рейтингу за неделю/месяц/всё время
  - кнопки имеют описание при наведении на них курсором
  - сообщения в чате отправляются нажатием кнопки "Enter"